---
v_k3s: v1.23.5+k3s1
ansible_user: root
server_ip: "{{ hostvars[groups['servers'][0]]['ansible_default_ipv4']['address'] }}"
node_token: "{{ hostvars[groups['servers'][0]]['node_token'] }}"
k3s_service_files:
  - k3s.service
  - k3s-agent.service
