---
- name: Uninstall k3s agent
  include: uninstall.yml
  when: run_option is defined and run_option == "uninstall"

- name: Install k3s agent
  include: install.yml
  when: run_option is not defined or run_option == "install"
