---
- name: k3s common
  hosts: servers, agents
  roles:
    - { role: common }

- name: k3s server
  hosts: servers
  roles:
    - { role: server }

- name: k3s agent
  hosts: agents
  roles:
    - { role: agent }