---
- name: Download k3 installation script
  hosts: servers, agents
  roles:
    - { role: common }

- name: Install k3s server
  hosts: servers
  roles:
    - { role: server }

- name: Install k3s agent
  hosts: agents
  roles:
    - { role: agent }