---
- name: Check k3s version output
  shell: k3s --version | cut -d ' ' -f 3
  register: k3s_installation_check

- debug: var=k3s_installation_check.stdout_lines

- name: Check if k3s.service file exists
  stat:
    path: /etc/systemd/system/{{ item }}
  with_items: "{{ k3s_service_files }}"
  register: k3s_file_check

- debug: var=k3s_file_check

- name: Download k3s install script
  get_url: 
    url: https://get.k3s.io
    dest: /tmp
    mode: a+x
    force: yes
